### ISSUE TITLE
Black Screen Only

### ISSUE THREAD

**Issue by jaysonl23** [liggiorgio/ar-collaborative#1]
So I tried to Open it and install the ar sandbox. It was installed in the and run but it has a black background no camera footage in the back. Im using the latest ar plug ins , could this be the problem?

**Comment by liggiorgio** [comment]
Hello, I believe this happens when XR subsystems fail to initialise. I'll try to replicate the issue and find a solution. Can you please include additional information about your tools? Unity version, AR Foundation & AR Core packages version. Also, please note that this repo only contains the ARC library and some sample scenes, so you must manually check additional Android and XR-related settings for new projects.

**Comment by liggiorgio** [comment]
I managed to make things work. You can try and follow these steps as well.

- Fresh-install **Unity 2020.3.29f1 LTS** via Unity Hub. Install the included Android SDK/NDK and the OpenJDK as well.
- Clone/download the repository: `git clone https://github.com/liggiorgio/ar-collaborative.git`.
- In the Unity Hub, in the Projects tab, click Open and select the top-level project folder (_ar-collaborative_)
- Wait for Unity to create project files. Ignore the warnings about missing packages and broken code. You're going to manually include the missing packages (AR Foundation, ARCore/ARKit XR Plugins, Multiplayer HLAPI) at a second moment.
- Once everything's loaded, open the Package Manager via **Window > Package Manager**. Select _Packages: Unity Registry_ and install the following packages: **AR Foundation 4.1.9**, **ARCore XR Plugin 4.1.9** (if deploying on Android) and/or **ARKit XR Plugin 4.1.9** (if deploying on iOS), **Multiplayer HLAPI 1.1.1**.
- In **Preferences > External Tools**: check the Android checkboxes to make Unity use the recommended SDK/NDK/JDK/Gradle.
- In **Project Settings > Player > Other Settings**: uncheck **Auto Graphics API** and only include _OpenGLES3_ in the **Graphics APIs** list. Set **Minimum API Level** to _Android 7.0 'Nougat (API level 24)_.
- In **Project Settings > XR Plug-in Management**: check the **ARCore** checkbox in the **Plug-in Providers** list.

Make sure you're using the Unity, AR Foundation and ARCore/ARKit XR Plugin versions detailed above. This requirement is due to the Multiplayer HLAPI being deprecated but currently required to manage networking. Unity versions >= 2021 don't support HLAPI anymore. AR packages version 4.1.9 are verified to properly work on Unity 2020.3.29f1, which is an LTS and quite a stable version of the editor.

A new version of AR Collaborative may get rid of HLAPI and work on higher versions of Unity, but this requires Unity to release a new, stable networking library. One could rewrite the scripts dealing with networking to use Photon or other libraries, but I'm yet to do so in the near future.

Please let me know if this helped you solve the black screen problem, so I can mark this issue as solved.

**Comment by jaysonl23** [comment]
sorry for the very very late response, Yes I managed to make it work. Sorry for the delay in relaying the message.
